# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
                ('questionnaire_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_lesson', to='app01.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('student_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_lesson', to='app01.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Trouble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('trouble_questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trouble_questionnaire', to='app01.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='result_student',
            field=models.ManyToManyField(related_name='result_student', to='app01.Student'),
        ),
        migrations.AddField(
            model_name='result',
            name='result_trouble',
            field=models.ManyToManyField(related_name='result_trouble', to='app01.Trouble'),
        ),
        migrations.AddField(
            model_name='option',
            name='option_trouble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_trouble', to='app01.Trouble'),
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_trouble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_trouble', to='app01.Trouble'),
        ),
    ]
