# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171205_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='genre_trouble',
        ),
        migrations.AddField(
            model_name='genre',
            name='genre_trouble',
            field=models.ManyToManyField(related_name='genre_trouble', to='app01.Trouble'),
        ),
        migrations.RemoveField(
            model_name='option',
            name='option_trouble',
        ),
        migrations.AddField(
            model_name='option',
            name='option_trouble',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='option_trouble', to='app01.Trouble'),
            preserve_default=False,
        ),
    ]
